name: Upload dotnet package

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/PinchPayments/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}

      - name: Build
        run: dotnet build --configuration Release

      - name: Create the package
        run: dotnet pack --configuration Release -p:PackageVersion=${{ steps.get_version.outputs.VERSION }}

      - name: Publish the package to GPR
        working-directory: ./src/Pinch.SDK
        run: dotnet nuget push ./bin/Release/*.nupkg

      #- name: Publish Github Release
      #  uses: marvinpinto/action-automatic-releases@v1.2.1
      #  with:
      #    title: v${{ steps.get_version.outputs.VERSION }}
      #    repo_token: ${{ secrets.GITHUB_TOKEN }}
      #    prerelease: false
      #    files: ./src/Pinch.SDK/bin/Release/*.nupkg

      - name: Create Github release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v${{ steps.get_version.outputs.VERSION }}" \
              "./src/Pinch.SDK/bin/Release/Pinch.SDK.${{ steps.get_version.outputs.VERSION }}.nupkg"
              --repo="$GITHUB_REPOSITORY" \
              --title="v${{ steps.get_version.outputs.VERSION }}" \
              --generate-notes