name: Upload dotnet package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/PinchPayments/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Build
        run: dotnet build --configuration Release

      - name: Create the package
        run: dotnet pack --configuration Release

      - name: Publish the package to GPR
        working-directory: ./src/Pinch.SDK
        run: dotnet nuget push ./bin/Release/*.nupkg